
spring: 
  datasource: 
    hikari: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      username: 
      password: 

logging: 
  level: 
    org.springframework: INFO

mybatis: 
  #config-location: classpath:mybatis-config.xml
  configuration: 
    map-underscore-to-camel-case: true
